//Pragma comments
#pragma once

//Component type macro definitions
#define COMPONENT_TYPE_DEFAULT 0
#define COMPONENT_TYPE_TRANSFORM 1
#define COMPONENT_TYPE_STATIC_MESH 2
#define COMPONENT_TYPE_STREAM_MESH 3
#define COMPONENT_TYPE_MATERIAL 4
#define COMPONENT_TYPE_CAMERA 5
#define COMPONENT_TYPE_SCRIPT 6
#define COMPONENT_TYPE_PARTICLE_SYSTEM 7
#define COMPONENT_TYPE_GUI_OBJECT 8
#define COMPONENT_TYPE_GUI_CHARACTER 9
#define COMPONENT_TYPE_GUI_STRING 10
#define COMPONENT_TYPE_GUI_HORIZONTAL_SLIDER 11
#define COMPONENT_TYPE_DIRECTIONAL_LIGHT 12
#define COMPONENT_TYPE_POINT_LIGHT 13
#define COMPONENT_TYPE_EVENT_LISTENER 14